version: '3.8'

services:

  # Servicio para la base de datos
  # nombre del servicio
  db:
    # imagen
    image: mysql:latest
    # variable de entorno
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user 
      MYSQL_DATABASE: my_database
      # persistencia 
    volumes: 
      - db_data:/var/lib/mysql
      # red
    networks:
      - backend
  # Servicio para la aplicacion web
      # nombre del servicio
  web:
    # imagen
    image: nginx:alpine
    # el servicio web va a depender del servicio de los datos. el de datos se v aa ejecutar siempre primero.
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - html_volume:/usr/share/nginx/html
      - config_volume:/etc/nginx/conf.d
    networks:
      - frontend
      - backend

volumes:
  html_volume:
  config_volume:
  db_data:

networks:
  frontend:
  backend:
